### ISSUE TITLE
Refactor all string constants as a resource string

### ISSUE THREAD

**Issue by AbhigyaKrishna** [AbhigyaKrishna/Bourbon#1]
![image](https://github.com/user-attachments/assets/657423eb-86be-4b5a-bcfe-aaf98b92de6f)

**Comment by rubenquadros** [comment]
These should go into string resource. I can pick this up!

**Comment by AbhigyaKrishna** [comment]
Sure go ahead! Assigned you.

**Comment by rubenquadros** [comment]
I'm guessing `key.properties` is required without which the project does not build. Commenting its usage from gradle files does the trick. However, you can probably have a step to check if the file exists and then read it. Also skip the signing if the file is not present.
``` 
//check if file exists before loading
load(rootDir.resolve("key.properties").reader())
```

**Comment by AbhigyaKrishna** [comment]
Its required as google authentication won't work while signing with the debug key.

**Comment by rubenquadros** [comment]
Yes got it. Since `key.properties` and `google-services.json` files are not present, I'm not able to build the app. I have extracted the strings to resources. So the PR should be good!
